/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_GSM_SMS
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_GSM_SMS

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_GSM_SMS_send_message (DBusGProxy *proxy, const char * IN_recipient_number, const char * IN_contents, const GHashTable* IN_properties, gint* OUT_transaction_index, GError **error)

{
  return dbus_g_proxy_call (proxy, "SendMessage", error, G_TYPE_STRING, IN_recipient_number, G_TYPE_STRING, IN_contents, dbus_g_type_get_map ("GHashTable", G_TYPE_STRING, G_TYPE_VALUE), IN_properties, G_TYPE_INVALID, G_TYPE_INT, OUT_transaction_index, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_GSM_SMS_send_message_reply) (DBusGProxy *proxy, gint OUT_transaction_index, GError *error, gpointer userdata);

static void
org_freesmartphone_GSM_SMS_send_message_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_transaction_index;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_transaction_index, G_TYPE_INVALID);
  (*(org_freesmartphone_GSM_SMS_send_message_reply)data->cb) (proxy, OUT_transaction_index, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_GSM_SMS_send_message_async (DBusGProxy *proxy, const char * IN_recipient_number, const char * IN_contents, const GHashTable* IN_properties, org_freesmartphone_GSM_SMS_send_message_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "SendMessage", org_freesmartphone_GSM_SMS_send_message_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_recipient_number, G_TYPE_STRING, IN_contents, dbus_g_type_get_map ("GHashTable", G_TYPE_STRING, G_TYPE_VALUE), IN_properties, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_GSM_SMS */

G_END_DECLS
