/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_IdleNotifier
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_IdleNotifier

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_Device_IdleNotifier_get_state (DBusGProxy *proxy, char ** OUT_status, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetState", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_status, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_Device_IdleNotifier_get_state_reply) (DBusGProxy *proxy, char * OUT_status, GError *error, gpointer userdata);

static void
org_freesmartphone_Device_IdleNotifier_get_state_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_status;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_status, G_TYPE_INVALID);
  (*(org_freesmartphone_Device_IdleNotifier_get_state_reply)data->cb) (proxy, OUT_status, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_Device_IdleNotifier_get_state_async (DBusGProxy *proxy, org_freesmartphone_Device_IdleNotifier_get_state_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetState", org_freesmartphone_Device_IdleNotifier_get_state_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_Device_IdleNotifier_set_state (DBusGProxy *proxy, const char * IN_status, GError **error)

{
  return dbus_g_proxy_call (proxy, "SetState", error, G_TYPE_STRING, IN_status, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_Device_IdleNotifier_set_state_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_freesmartphone_Device_IdleNotifier_set_state_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_freesmartphone_Device_IdleNotifier_set_state_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_Device_IdleNotifier_set_state_async (DBusGProxy *proxy, const char * IN_status, org_freesmartphone_Device_IdleNotifier_set_state_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "SetState", org_freesmartphone_Device_IdleNotifier_set_state_async_callback, stuff, g_free, G_TYPE_STRING, IN_status, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_IdleNotifier */

G_END_DECLS
