/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_Input
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_Input

#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_Input */

G_END_DECLS
