/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_PowerSupply
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_PowerSupply

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_Device_PowerSupply_get_info (DBusGProxy *proxy, GHashTable** OUT_properties, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetInfo", error, G_TYPE_INVALID, dbus_g_type_get_map ("GHashTable", G_TYPE_STRING, G_TYPE_VALUE), OUT_properties, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_Device_PowerSupply_get_info_reply) (DBusGProxy *proxy, GHashTable *OUT_properties, GError *error, gpointer userdata);

static void
org_freesmartphone_Device_PowerSupply_get_info_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  GHashTable* OUT_properties;
  dbus_g_proxy_end_call (proxy, call, &error, dbus_g_type_get_map ("GHashTable", G_TYPE_STRING, G_TYPE_VALUE), &OUT_properties, G_TYPE_INVALID);
  (*(org_freesmartphone_Device_PowerSupply_get_info_reply)data->cb) (proxy, OUT_properties, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_Device_PowerSupply_get_info_async (DBusGProxy *proxy, org_freesmartphone_Device_PowerSupply_get_info_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetInfo", org_freesmartphone_Device_PowerSupply_get_info_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_Device_PowerSupply_get_capacity (DBusGProxy *proxy, gint* OUT_energy, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetCapacity", error, G_TYPE_INVALID, G_TYPE_INT, OUT_energy, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_Device_PowerSupply_get_capacity_reply) (DBusGProxy *proxy, gint OUT_energy, GError *error, gpointer userdata);

static void
org_freesmartphone_Device_PowerSupply_get_capacity_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_energy;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_energy, G_TYPE_INVALID);
  (*(org_freesmartphone_Device_PowerSupply_get_capacity_reply)data->cb) (proxy, OUT_energy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_Device_PowerSupply_get_capacity_async (DBusGProxy *proxy, org_freesmartphone_Device_PowerSupply_get_capacity_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetCapacity", org_freesmartphone_Device_PowerSupply_get_capacity_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_Device_PowerSupply_get_power_status (DBusGProxy *proxy, char ** OUT_status, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetPowerStatus", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_status, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_Device_PowerSupply_get_power_status_reply) (DBusGProxy *proxy, char * OUT_status, GError *error, gpointer userdata);

static void
org_freesmartphone_Device_PowerSupply_get_power_status_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_status;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_status, G_TYPE_INVALID);
  (*(org_freesmartphone_Device_PowerSupply_get_power_status_reply)data->cb) (proxy, OUT_status, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_Device_PowerSupply_get_power_status_async (DBusGProxy *proxy, org_freesmartphone_Device_PowerSupply_get_power_status_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetPowerStatus", org_freesmartphone_Device_PowerSupply_get_power_status_async_callback, stuff, g_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_Device_PowerSupply */

G_END_DECLS
